/*drop table if exists FLIGHTMST;
CREATE TABLE
FLIGHTMST(FL_ID integer PRIMARY KEY AUTO_INCREMENT , FL_ORIGIN VARCHAR(200) DEFAULT NULL, FL_DESTINATION VARCHAR(200) DEFAULT NULL, 
FL_PROVIDER VARCHAR(200) DEFAULT NULL, FL_PRICE decimal default 0.0, FL_DEP_TIME date DEFAULT NULL, FL_ARR_TIME date DEFAULT NULL);
*/